version: '3.3'

services:
  web:
    image: dodobas/waterboard
    command: ./utils/wait-for.sh db:5432 -- uwsgi --ini uwsgi.ini
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - SECRET_FILE=waterboard-secret.py
      - SERVICE_PORT=8008
    secrets:
      - waterboard-secret.py
    depends_on:
      - db
      - rabbitmq
    networks:
      - wb-infra
    volumes:
      - ./media:/data/media
      - ./cache:/data/cache
      - ./logs:/data/logs
      - ./static:/data/static
    deploy:
      replicas: 2


  worker:
    image: dodobas/waterboard
    command: ./utils/wait-for.sh db:5432 -- celery worker -A event_mapper.celery -l info -c 1
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - SECRET_FILE=waterboard-secret.py
    secrets:
      - waterboard-secret.py
    depends_on:
      - db
      - rabbitmq
    networks:
      - wb-infra
    volumes:
      - ./media:/data/media
      - ./cache:/data/cache
      - ./logs:/data/logs
    deploy:
      replicas: 1


  scheduler:
    image: dodobas/waterboard
    command: celery beat -A event_mapper.celery -l info
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - SECRET_FILE=waterboard-secret.py
    secrets:
      - waterboard-secret.py
    depends_on:
      - db
      - rabbitmq
    networks:
      - wb-infra
    deploy:
      replicas: 1


  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_NODENAME=rabbitmq
    networks:
      - wb-infra
    deploy:
      replicas: 1

  db:
    image: mdillon/postgis:10-alpine
    environment:
      - POSTGRES_USER=docker
      - POSTGERS_PASSWORD=docker
      - POSTGRES_DB=base_db
    networks:
      - wb-infra
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    deploy:
      replicas: 1

secrets:
  waterboard-secret.py:
    external: true


networks:
  wb-infra:
    external: true
