version: '3.1'

services:
  web:
    build:
      context: django_project
    command: ./utils/wait-for.sh db:5432 -t 60 -- python manage.py runserver 0.0.0.0:8000
    # command: ./utils/wait-for.sh db:5432 -t 60 -- uwsgi --ini uwsgi.ini
    depends_on:
      - db
      - redis
    volumes:
      - ./django_project:/project
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev_docker
      - SERVICE_PORT=8000

  worker:
    build:
      context: django_project
    command: ./utils/wait-for.sh db:5432 -t 60 -- celery worker -A core.celery -l info -c 1
    depends_on:
      - db
      - redis
    volumes:
      - ./django_project:/project
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev_docker

  scheduler:
    build:
      context: django_project
    command: celery beat -A core.celery -l info
    depends_on:
      - redis
    volumes:
      - ./django_project:/project
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev_docker

  redis:
    image: redis:4-alpine

  db:
    image: mdillon/postgis:10-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGERS_PASSWORD=docker
